Python Interpreter = /nfs/users/ext_amaya.dharmasiri/miniconda3/envs/dassl/bin/python
which nvcc =  /usr/local/cuda/bin/nvcc
nvcc --version =  nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2020 NVIDIA Corporation Built on Wed_Jul_22_19:09:09_PDT_2020 Cuda compilation tools, release 11.0, V11.0.221 Build cuda_11.0_bu.TC445_37.28845127_0
CUDA_VISIBLE_DEVICES =  0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
+ DATA=/nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/data
+ TRAINER=CoOp
+ DATASET=
+ imagenetLT
/var/spool/slurm/d/job45113/slurm_script: line 42: imagenetLT: command not found
+ CFG=rn50_cvlp/rn50_wikipromptcvlp
+ CTP=
+ end
/var/spool/slurm/d/job45113/slurm_script: line 44: end: command not found
+ NCTX=16
+ SHOTS=16
+ CSC=False
+ PRETRAINED_BACKBONE=/nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/checkpoints/pretrain_r50_original/checkpoint_50.pth
+ for SEED in 1
+ DIR=output//CoOp/rn50_cvlp/rn50_wikipromptcvlp_16shots/nctx16_cscFalse_ctp/seed1
+ '[' -d output//CoOp/rn50_cvlp/rn50_wikipromptcvlp_16shots/nctx16_cscFalse_ctp/seed1 ']'
+ /nfs/users/ext_amaya.dharmasiri/miniconda3/envs/dassl/bin/python -u train.py --root /nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/data --seed 1 --trainer CoOp --dataset-config-file configs/datasets/.yaml --config-file configs/trainers/CoOp/rn50_cvlp/rn50_wikipromptcvlp.yaml --output-dir output//CoOp/rn50_cvlp/rn50_wikipromptcvlp_16shots/nctx16_cscFalse_ctp/seed1 --pretrained_backbone /nfs/users/ext_amaya.dharmasiri/repos/VL-LTR/checkpoints/pretrain_r50_original/checkpoint_50.pth TRAINER.COOP.N_CTX 16 TRAINER.COOP.CSC False TRAINER.COOP.CLASS_TOKEN_POSITION DATASET.NUM_SHOTS 16
/nfs/users/ext_amaya.dharmasiri/repos/CoOp/clip/clip.py:23: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
Traceback (most recent call last):
  File "train.py", line 217, in <module>
    main(args)
  File "train.py", line 133, in main
    cfg = setup_cfg(args)
  File "train.py", line 115, in setup_cfg
    cfg.merge_from_file(args.dataset_config_file)
  File "/nfs/users/ext_amaya.dharmasiri/miniconda3/envs/dassl/lib/python3.8/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/datasets/.yaml'
